### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by eyal-mor**
# Overview

**Github Issue**: {LINK TO ISSUE}

## Checklist
 
 
- [ ] My pull request title follows the format `<username>/<gh-issue-#number>:<short-description>`
- [ ] My code passes existing unit tests
- [ ] My code follows the code style set for the project
- [ ] I have added at least one reviewer for this PR

### CODE REVIEW

**Comment by eyalmor-ent** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by eyal-mor** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by eyal-mor** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by eyal-mor** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request closed without merging**
